name: Generate CV PDF

on:
  push:
    paths:
      - '_data/cv.json'
      - 'generate_cv_pdf.py'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install reportlab
    
    - name: Generate CV PDF
      run: |
        python generate_cv_pdf.py
    
    - name: Check if PDF was generated
      run: |
        if [ -f "files/cv.pdf" ]; then
          echo "✓ PDF generated successfully"
          ls -la files/cv.pdf
        else
          echo "✗ PDF generation failed"
          exit 1
        fi
    
    - name: Commit and push PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if [ -f "files/cv.pdf" ]; then
          git add files/cv.pdf
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update CV PDF [skip ci]"
            git push
            echo "✓ PDF committed and pushed"
          fi
        fi
    
    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v3
      with:
        name: cv-pdf
        path: files/cv.pdf
        retention-days: 30